#! /bin/bash

cd $(dirname $0)
source  $(dirname $0)/profile

while read -r line ; do
  case $line in
    S*)
      # info
      sys_infos="%{r}${line#?}"
      ;;
    W*)
      wm_infos=""
      IFS=':'
      set -- ${line#?}
      while [ $# -gt 0 ] ; do
        item=$1
        name=${item#?}
        case $item in
          [OFU]*)
            # active desktop
            wm_infos="$wm_infos$active"
            ;;
          o*)
            # inactive but occupied desktop
            wm_infos="$wm_infos$occupied"
            ;;
          f*)
            # inactive desktop
            wm_infos="$wm_infos$free"
            ;;
          u*)
            # urgent desktop
            wm_infos="$wm_infos$urgent"
            ;;
          L*)
            # layout
            # layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
            wm_infos="$wm_infos $layout"
            ;;
        esac
        shift
      done
      ;;
  esac
  printf "%s\n" "%{l}$wm_infos%{r} $sys_infos"
done
