#! /bin/sh


PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=20
#PANEL_FONT="-*-terminus-medium-r-normal-*-12-*-*-*-c-*-*-1"

#PANEL_FONT_SYMBOL="-misc-stlarch-medium-r-normal--10-100-75-75-c-80-iso10646-1"
#PANEL_FONT="-benis-lemon-medium-r-normal--10-110-75-75-m-50-iso8859-1"
PANEL_FONT="-*-tewi-*-*-*-*-*-*-*-*-*-*-*"

export PANEL_FIFO PANEL_HEIGHT PANEL_FONT_FAMILY PANEL_FONT PANEL_FONT_SYMBOL

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

source ~/.config/bspwm/oldpanel/panel_colors

cat "$PANEL_FIFO" |  ~/.config/bspwm/oldpanel/panel_bar | lemonbar -g x$PANEL_HEIGHT -f "$PANEL_FONT" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
