#! /bin/sh

PANEL_FONT="-*-terminus-bold-r-normal-*-12-*-*-*-c-*-*-1"
#PANEL_FONT="-*-creep-*-*-*-*-17-*-*-*-*-*-*-*"
PANEL_FONT_SYMBOL="-*-stlarch-*-*-*-*-*-*-*-*-*-*-*-*"
PANEL_HEIGHT=24

export PANEL_FONT PANEL_HEIGHT PANEL_FONT_SYMBOL

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc control --subscribe > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

source ~/.config/bspwm/newpanel/panel_colors

cat "$PANEL_FIFO" | ~/.config/bspwm/newpanel/panel_bar | \
  lemonbar -g x$PANEL_HEIGHT -f $PANEL_FONT -f $PANEL_FONT_SYMBOL -F $COLOR_FOREGROUND \
  -B $COLOR_BACKGROUND &

wait
